//! The typeDiagram compatibility corpus [typediagram.delivery.baseline].
//!
//! Every fixture in `tests/typediagram/corpus` carries the model JSON the
//! upstream parser and model builder produce for it, generated by
//! `scripts/typediagram-oracle.mjs` from a real typeDiagram checkout. This
//! suite parses and resolves the same fixture with the *Rust* front end and
//! requires the two models to be structurally identical.
//!
//! That is the whole point of the corpus. dmx never runs typeDiagram in
//! production — no Node, no npm package, no `typediagram` executable, no
//! network — so the only thing that can keep the two in step is a gate that
//! fails when they diverge. Upstream language drift shows up here, in CI,
//! rather than as Dart somebody's build generated wrongly.

// [TEST-RULES] admits `expect` in a test: a fixture that cannot be built is a
// broken test, and unwinding at the point of failure names it better than any
// `Result` plumbing would. Production code is still held to `unwrap_used` and
// `expect_used` at deny — this relaxation is `cfg(test)`-scoped on purpose.
#![cfg_attr(
    test,
    allow(
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::panic,
        clippy::indexing_slicing,
        clippy::arithmetic_side_effects
    )
)]

use std::fs;
use std::path::PathBuf;

use dmx::typediagram::json::{SCHEMA_VERSION, to_json};
use dmx::typediagram::model::Model;
use dmx::typediagram::parser::parse;

/// Where the fixtures live.
fn corpus() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("typediagram")
        .join("corpus")
}

/// Every `*.td` fixture, in a stable order, with its oracle JSON beside it.
fn fixtures() -> Vec<(String, String, serde_json::Value)> {
    let mut found: Vec<(String, String, serde_json::Value)> = fs::read_dir(corpus())
        .expect("the corpus directory")
        .filter_map(|entry| {
            let path = entry.expect("a corpus entry").path();
            if path.extension()? != "td" {
                return None;
            }
            let name = path.file_name()?.to_string_lossy().into_owned();
            let oracle = path.with_extension("model.json");
            let expected = serde_json::from_str(&fs::read_to_string(&oracle).unwrap_or_else(|e| {
                panic!(
                    "{}: no oracle model beside it ({e}); run \
                     `node scripts/typediagram-oracle.mjs --typediagram <checkout>`",
                    oracle.display()
                )
            }))
            .unwrap_or_else(|e| panic!("{}: oracle is not JSON: {e}", oracle.display()));
            Some((
                name,
                fs::read_to_string(&path).expect("a fixture"),
                expected,
            ))
        })
        .collect();
    found.sort_by(|a, b| a.0.cmp(&b.0));
    assert!(
        found.len() >= 5,
        "the compatibility corpus must cover the language reference, found {} fixture(s)",
        found.len()
    );
    found
}

/// The model JSON dmx's own front end produces for `source`.
fn dmx_model(name: &str, source: &str) -> serde_json::Value {
    let diagram = parse(source).unwrap_or_else(|e| panic!("{name} did not parse:\n{e}"));
    let model = Model::resolve(diagram).unwrap_or_else(|e| panic!("{name} did not resolve:\n{e}"));
    to_json(&model)
}

/// [typediagram.delivery.baseline]: the Rust model and the upstream model
/// agree, declaration for declaration, over the whole corpus.
#[test]
fn the_rust_model_matches_the_upstream_oracle() {
    for (name, source, expected) in fixtures() {
        let actual = dmx_model(&name, &source);
        assert_eq!(
            actual,
            expected,
            "{name}: the Rust model diverged from the typeDiagram oracle\n\
             dmx:      {}\n\
             upstream: {}",
            serde_json::to_string_pretty(&actual).unwrap_or_default(),
            serde_json::to_string_pretty(&expected).unwrap_or_default(),
        );
    }
}

/// [typediagram.delivery.baseline]: the corpus is pinned to one schema
/// version, and a bump has to be a deliberate change to this repository.
#[test]
fn the_corpus_pins_one_model_schema_version() {
    for (name, _, expected) in fixtures() {
        assert_eq!(
            expected["version"],
            serde_json::json!(SCHEMA_VERSION),
            "{name}: the oracle was generated at a different model schema version; \
             DMX8007 exists for exactly this"
        );
    }
}

/// [typediagram.delivery.baseline]: the corpus actually covers the language
/// reference, rather than five fixtures that happen to agree about records.
#[test]
fn the_corpus_covers_every_declaration_form() {
    let mut kinds: Vec<String> = Vec::new();
    let mut features = (false, false, false, false, false, false);
    for (_, _, expected) in fixtures() {
        for decl in expected["decls"].as_array().expect("decls") {
            if let Some(kind) = decl["kind"].as_str()
                && !kinds.iter().any(|seen| seen == kind)
            {
                kinds.push(kind.to_owned());
            }
            features.0 |= !decl["generics"].as_array().is_none_or(Vec::is_empty);
            features.1 |= decl["untagged"] == serde_json::json!(true);
            features.2 |= decl["targeting"].is_object();
            for variant in decl["variants"].as_array().into_iter().flatten() {
                features.3 |= variant["discriminant"].is_string();
                features.4 |= variant["fields"][0]["name"] == serde_json::json!("_0");
            }
            for signature in decl["signatures"].as_array().into_iter().flatten() {
                features.5 |= signature["async"] == serde_json::json!(true);
            }
        }
    }
    kinds.sort_unstable();
    assert_eq!(kinds, ["alias", "function", "record", "union"]);
    assert_eq!(
        features,
        (true, true, true, true, true, true),
        "generics, untagged, targeting, discriminants, tuple variants, and async \
         signatures must all appear in the corpus"
    );
}

/// [typediagram.model]: nested type arguments survive the whole round trip, so
/// a `Map<String, List<Option<Decimal>>>` in the corpus is not silently
/// flattened by either side.
#[test]
fn deeply_nested_arguments_survive() {
    let (name, source, _) = fixtures()
        .into_iter()
        .find(|(name, ..)| name == "scalars.td")
        .expect("the scalars fixture");
    let model = dmx_model(&name, &source);
    let index = model["decls"][0]["fields"]
        .as_array()
        .expect("fields")
        .iter()
        .find(|field| field["name"] == serde_json::json!("index"))
        .expect("the index field");
    assert_eq!(index["type"]["name"], serde_json::json!("Map"));
    assert_eq!(index["type"]["args"][1]["name"], serde_json::json!("List"));
    assert_eq!(
        index["type"]["args"][1]["args"][0]["name"],
        serde_json::json!("Option")
    );
    assert_eq!(
        index["type"]["args"][1]["args"][0]["args"][0]["name"],
        serde_json::json!("Decimal")
    );
}
