'use strict';

// Which paths a workspace folder is watched at [editor.extension.paths].
//
// `lib` is the answer for one package opened on its own, and the wrong answer
// for everything else. A repo holding its packages under `examples/`, `apps/`
// or `packages/` has no `lib` at the top, so a watcher that only ever looks
// there watches nothing at all — and nothing at all is indistinguishable, from
// the editor, from a generator that has stopped working.
//
// So: what the setting names, if it exists, and otherwise every Dart package
// this folder actually holds — plus every `*.dmx.md` document in it, because a
// document generates Dart with no annotated Dart source to find it by
// [typediagram.documents].

const fs = require('node:fs');
const path = require('node:path');

/// How far down a workspace is searched for packages. Deep enough for
/// `examples/<name>` and `packages/<name>/<name>`, shallow enough that opening
/// a large tree costs a handful of directory reads.
const MAX_DEPTH = 3;

/// Directories that never hold a package worth generating into: build output,
/// dependencies, and the platform folders a Flutter app carries.
const SKIPPED = new Set([
  'node_modules',
  'build',
  'target',
  'android',
  'ios',
  'macos',
  'linux',
  'windows',
  'web',
]);

/// Whether this directory is a Dart package with sources in it.
function isPackage(directory) {
  return (
    fs.existsSync(path.join(directory, 'pubspec.yaml')) &&
    fs.existsSync(path.join(directory, 'lib'))
  );
}

/// The directories worth descending into, hidden ones and build output aside.
function children(directory) {
  try {
    return fs
      .readdirSync(directory, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .filter((name) => !name.startsWith('.') && !SKIPPED.has(name))
      .sort();
  } catch {
    return [];
  }
}

/// Every Dart package under `root`, as workspace-relative paths to its `lib`.
///
/// A package's own subdirectories are not searched: `example/` inside a package
/// is generated by watching the package that contains it.
function packageLibraries(root, depth = MAX_DEPTH) {
  const found = [];
  for (const name of children(root)) {
    const directory = path.join(root, name);
    if (isPackage(directory)) {
      found.push(path.join(name, 'lib'));
    } else if (depth > 1) {
      found.push(...packageLibraries(directory, depth - 1).map((relative) => path.join(name, relative)));
    }
  }
  return found;
}

/// The suffix that makes a Markdown file one dmx generates from.
const DOCUMENT_SUFFIX = '.dmx.md';

/// Every `*.dmx.md` document under `root`, as workspace-relative file paths.
///
/// Files rather than their directories: `dmx watch` takes either, and naming
/// the document watches exactly it, where naming `docs/` would watch a whole
/// tree of prose for changes that can never matter. A package's own
/// subdirectories ARE searched, unlike `packageLibraries` — a document
/// normally lives in the package whose `lib` it generates into.
function documents(root, depth = MAX_DEPTH + 1) {
  const found = [];
  let entries = [];
  try {
    entries = fs.readdirSync(root, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name));
  } catch {
    return found;
  }
  for (const entry of entries) {
    if (entry.name.startsWith('.') || SKIPPED.has(entry.name)) {
      continue;
    }
    if (entry.isFile() && entry.name.endsWith(DOCUMENT_SUFFIX)) {
      found.push(entry.name);
    } else if (entry.isDirectory() && depth > 1) {
      found.push(...documents(path.join(root, entry.name), depth - 1).map((relative) => path.join(entry.name, relative)));
    }
  }
  return found;
}

/// The paths to hand `dmx`, in the order they were worked out.
///
/// `configured` is what somebody set explicitly, and it is honoured exactly:
/// naming paths means naming all of them. Left at the default, a folder is
/// watched at its own `lib` plus every package it holds, so opening a repo
/// generates the code in it whatever its layout is.
function watchTargets(root, configured, explicit) {
  const present = (configured ?? []).filter((relative) => fs.existsSync(path.join(root, relative)));
  if (explicit) {
    return present;
  }
  return [...new Set([...present, ...packageLibraries(root), ...documents(root)])];
}

module.exports = { documents, packageLibraries, watchTargets };
