/// What this package reports as its version [release.version].
///
/// The number below is not written by hand and must never be edited. It is
/// generated by this package's own macro worker, `tool/dmx/macros.dart`, which
/// reads `version:` straight out of `pubspec.yaml`. The pubspec declares the
/// version once; everything that reports one reads it from here. There is no
/// second place to forget.
///
/// dmx generating the package that dmx ships is deliberate: the worker uses
/// `package:dmx/macros.dart`, the same authoring API any project uses
/// [dartmacros.api].
library;

import '../dmx.dart';

/// This package's identity, as its pubspec declares it.
@dmx('packageVersion')
final class DmxPackage {
  //#region
  /// The version `pubspec.yaml` declares for this package.
  static const String version = '0.0.0';
  //#endregion
}
