//! Stage 1: tree-sitter front end (spec §6.1).
//!
//! Reads every top-level declaration a macro can be attached to — classes and
//! enums — along with their fields, values, abstract members, supertypes,
//! annotations, and the `//#region` dividers. Regions are located via CST
//! comment tokens, never regex over raw text (spec §11.3.2).
//!
//! The front end is deliberately macro-agnostic [architecture]: it reports what
//! the file *says*, and [`crate::macros`] decides what any of it means. That is
//! what lets a second macro cost a context builder and a template, rather than
//! a second front end.

use anyhow::{Result, anyhow, bail};
use std::collections::BTreeMap;
use tree_sitter::{Node, Parser, Tree};

/// The divider [emission.inline-backend.region-location]. Deliberately the bare, unlabelled VS Code folding
/// marker: editors collapse it for free, and a labelled `//#region Helpers`
/// stays the author's own.
pub const REGION_START: &str = "//#region";
/// The closing divider, paired with [`REGION_START`] by nesting.
pub const REGION_END: &str = "//#endregion";

/// The qualified divider dmx wrote before the bare one — `//#region
/// dmx:generated builtin/model@0.1.0 b3:… — DO NOT EDIT`. Still recognised as
/// machine-owned, so a file generated by an older dmx is regenerated (and
/// thereby migrated to the bare divider) instead of reported as damage.
const LEGACY_LABEL: &str = "dmx:generated";

/// Whether a comment opens a region, and whether that region is dmx's.
///
/// `Some(true)` is a machine-owned divider — bare, or legacy-qualified.
/// `Some(false)` is an author's labelled fold. `None` is not a divider at all:
/// `//#regionalise` is prose.
pub fn region_opener(comment: &str) -> Option<bool> {
    let label = comment.trim().strip_prefix(REGION_START)?;
    if label.is_empty() {
        return Some(true);
    }
    if !label.starts_with(char::is_whitespace) {
        return None;
    }
    Some(label.trim_start().starts_with(LEGACY_LABEL))
}

/// Whether a comment closes a region, in either the bare or the legacy form.
#[must_use]
pub fn is_region_end(comment: &str) -> bool {
    match comment.trim().strip_prefix(REGION_END) {
        Some(rest) => rest.is_empty() || rest.trim_start().starts_with(LEGACY_LABEL),
        None => false,
    }
}

#[derive(Debug, Clone)]
/// One annotation as it was written, arguments unevaluated.
///
/// `@dmx('union', {'discriminator': 'kind'})` arrives here already normalized
/// [surface.annotations]: `name` is the macro string the author wrote,
/// `args` are the map literal's entries, and `dmx` is set. Every other
/// annotation (`@override`, `@Deprecated`) keeps its own name with `dmx`
/// clear, so it can never collide with a macro lookup.
pub struct RawAnnotation {
    /// The macro name inside `@dmx(…)`, or the foreign annotation's name
    /// without the `@`.
    pub name: String,
    /// Named arguments as (label, raw Dart source of the value) — for a
    /// `@dmx`, the entries of its map literal.
    pub args: Vec<(String, String)>,
    /// Whether this is a `@dmx(…)` trigger rather than a foreign annotation.
    pub dmx: bool,
}

impl RawAnnotation {
    /// The raw source of one named argument.
    #[must_use]
    pub fn arg(&self, label: &str) -> Option<&str> {
        self.args
            .iter()
            .find(|(l, _)| l == label)
            .map(|(_, v)| v.as_str())
    }

    /// A boolean flag: present-without-`false` reads as true, matching how an
    /// absent map entry defaults.
    #[must_use]
    pub fn flag(&self, label: &str) -> Option<bool> {
        self.arg(label).map(|v| v.trim() != "false")
    }
}

/// Anything a macro can ask for an annotation by name.
///
/// Written once because the question is the same question wherever it is
/// asked: a field, a parameter, and a declaration all carry a list and all get
/// looked up the same way.
pub trait Annotated {
    /// Every annotation attached to this item.
    fn annotations(&self) -> &[RawAnnotation];

    /// The `@dmx` trigger with this macro name, if this item carries one.
    fn annotation(&self, name: &str) -> Option<&RawAnnotation> {
        self.annotations().iter().find(|a| a.dmx && a.name == name)
    }
}

#[derive(Debug, Clone)]
/// One instance `final` field of a class.
pub struct RawField {
    /// The field name, as the author wrote it.
    pub name: String,
    /// Explicit type source text, e.g. `List<String>`. Absent for `final x = …`.
    pub type_text: Option<String>,
    /// `@dmx('key')`, `@dmx('column')`, `@dmx('check.…')`, and anything else attached to it.
    pub annotations: Vec<RawAnnotation>,
    /// The default this field's constructor parameter declares, verbatim —
    /// `this.jobs = 4` is `4`. A macro that has to state a default (`@dmx('cli')`
    /// usage text, an absent `@dmx('query')` parameter) reads the author's own rather
    /// than inventing one.
    pub default_value: Option<String>,
}

impl Annotated for RawField {
    fn annotations(&self) -> &[RawAnnotation] {
        &self.annotations
    }
}

/// One constant of an enum declaration.
#[derive(Debug, Clone)]
pub struct RawValue {
    /// The constant name, as the author wrote it.
    pub name: String,
    /// `@dmx('value', {'wire': , 'label': })` and anything else attached to it.
    pub annotations: Vec<RawAnnotation>,
}

/// A parameter of an abstract member.
#[derive(Debug, Clone)]
pub struct RawParam {
    /// The parameter name.
    pub name: String,
    /// Explicit type source text, when the author wrote one.
    pub type_text: Option<String>,
    /// Declared inside `{…}` rather than positionally.
    pub is_named: bool,
    /// Declared `required`.
    pub is_required: bool,
    /// Dart source of the default value, when the author wrote one.
    pub default_value: Option<String>,
    /// `@dmx('query')`, `@dmx('body')` — how the parameter travels [catalogue.macros].
    pub annotations: Vec<RawAnnotation>,
}

impl Annotated for RawParam {
    fn annotations(&self) -> &[RawAnnotation] {
        &self.annotations
    }
}

/// An abstract member — a method or getter with a signature and no body. These
/// are what an interface *is*, and what `@dmx('fake')` and `@dmx('restClient')` implement.
#[derive(Debug, Clone)]
pub struct RawMethod {
    /// The member name.
    pub name: String,
    /// Explicit return type source text, when the author wrote one.
    pub return_type: Option<String>,
    /// The parameters, positional ones first.
    pub params: Vec<RawParam>,
    /// `@dmx('get')`, `@dmx('post')`, and anything else attached to it.
    pub annotations: Vec<RawAnnotation>,
    /// A getter has no parameter list at all.
    pub is_getter: bool,
}

impl Annotated for RawMethod {
    fn annotations(&self) -> &[RawAnnotation] {
        &self.annotations
    }
}

/// An existing generated region inside a declaration body.
#[derive(Debug)]
pub struct Region {
    /// Byte offset of the first character of the `//#region` line (its indent).
    pub start: usize,
    /// Byte offset just past the `//#endregion` token.
    pub end: usize,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
/// Which kind of declaration a macro is attached to.
pub enum DeclKind {
    /// A `class`, in any of its modifier flavours.
    Class,
    /// An `enum`.
    Enum,
}

#[derive(Debug)]
/// One top-level declaration, as the file says it is.
pub struct RawDecl {
    /// Class or enum.
    pub kind: DeclKind,
    /// The declared name.
    pub name: String,
    /// Everything attached to the declaration itself.
    pub annotations: Vec<RawAnnotation>,
    /// `sealed`, `abstract`, `final`, `base`, `interface`, `mixin`.
    pub modifiers: Vec<String>,
    /// Source text of the type parameter list, e.g. `<T, K extends num>`.
    pub type_params: String,
    /// The `extends` clause's bare type name.
    pub extends: Option<String>,
    /// Bare type names from `implements`.
    pub interfaces: Vec<String>,
    /// Instance `final` fields, in source order.
    pub fields: Vec<RawField>,
    /// Enum constants, in source order. Empty for a class.
    pub values: Vec<RawValue>,
    /// Abstract members — what an interface leaves open.
    pub methods: Vec<RawMethod>,
    /// The machine-owned region, when the declaration already has one.
    pub region: Option<Region>,
    /// Why the region could not be located. Raised only if a macro needs it, so
    /// a malformed fold in an unannotated declaration is none of dmx's business.
    pub region_error: Option<String>,
    /// Byte offset of the body's closing `}` — the insertion point.
    pub close_brace: usize,
    /// An enum body only admits members after a `;` terminating its constants.
    pub values_terminated: bool,
}

impl Annotated for RawDecl {
    fn annotations(&self) -> &[RawAnnotation] {
        &self.annotations
    }
}

impl RawDecl {
    /// Whether the declaration was written with this modifier.
    #[must_use]
    pub fn has_modifier(&self, modifier: &str) -> bool {
        self.modifiers.iter().any(|m| m == modifier)
    }

    /// `Box<T, K extends num>` declares `<T, K>` at every use site.
    #[must_use]
    pub fn type_args(&self) -> String {
        let inner: Vec<&str> = self
            .type_params
            .trim_start_matches('<')
            .trim_end_matches('>')
            .split(',')
            .filter_map(|p| p.split_whitespace().next())
            .filter(|p| !p.is_empty())
            .collect();
        if inner.is_empty() {
            String::new()
        } else {
            format!("<{}>", inner.join(", "))
        }
    }
}

/// The tree-sitter front end, holding the parser across files [frontend].
pub struct Frontend {
    /// Reused across files: loading the grammar is the expensive part.
    parser: Parser,
}

/// `tree_sitter::Parser` is opaque, and its state is not something a
/// diagnostic could act on anyway — what matters is which grammar it holds.
impl std::fmt::Debug for Frontend {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Frontend")
            .field("grammar", &"dart")
            .finish()
    }
}

impl Frontend {
    /// Loads the Dart grammar, once per run.
    ///
    /// # Errors
    ///
    /// Fails when the Dart grammar cannot be loaded.
    pub fn new() -> Result<Self> {
        let mut parser = Parser::new();
        parser
            .set_language(&tree_sitter_dart::LANGUAGE.into())
            .map_err(|e| anyhow!("DMX1001: cannot load Dart grammar: {e}"))?;
        Ok(Self { parser })
    }

    /// Parses `src` into a CST, or says the grammar could not be driven.
    ///
    /// # Errors
    ///
    /// Fails when the parser cannot be driven over `src` at all.
    pub fn parse(&mut self, src: &str) -> Result<Tree> {
        self.parser
            .parse(src, None)
            .ok_or_else(|| anyhow!("DMX2000: parser returned no tree"))
    }

    /// Spec §10: any ERROR or MISSING node fails validation.
    ///
    /// # Errors
    ///
    /// Fails when `src` does not parse, naming the first position that did not.
    pub fn validate(&mut self, src: &str, origin: &str) -> Result<()> {
        let tree = self.parse(src)?;
        let mut cursor = tree.walk();
        loop {
            let node = cursor.node();
            if node.is_error() || node.is_missing() {
                let p = node.start_position();
                bail!(
                    "DMX4001: {origin} is not valid Dart at line {}, column {}",
                    p.row.saturating_add(1),
                    p.column.saturating_add(1)
                );
            }
            if cursor.goto_first_child() {
                continue;
            }
            while !cursor.goto_next_sibling() {
                if !cursor.goto_parent() {
                    return Ok(());
                }
            }
        }
    }

    /// Every top-level class and enum in `src`, annotated or not.
    ///
    /// Unannotated declarations are included on purpose: a macro resolves
    /// sibling declarations through them — `@dmx('union')` finds its variants, `@dmx('fake')`
    /// finds the interface it implements [frontend.name-index].
    ///
    /// # Errors
    ///
    /// Fails when `src` does not parse, or when a declaration has no name or body.
    pub fn declarations(&mut self, src: &str) -> Result<Vec<RawDecl>> {
        let tree = self.parse(src)?;
        let mut decls = Vec::new();
        let mut cursor = tree.root_node().walk();
        for node in tree.root_node().children(&mut cursor) {
            match node.kind() {
                "class_declaration" => decls.push(read_class(node, src)?),
                "enum_declaration" => decls.push(read_enum(node, src)?),
                _ => {}
            }
        }
        Ok(decls)
    }
}

/// Reads one `class_declaration` into the shape a macro sees.
fn read_class(node: Node<'_>, src: &str) -> Result<RawDecl> {
    let name = child_of_kind(node, "identifier")
        .map(|n| text(n, src).to_owned())
        .ok_or_else(|| anyhow!("DMX2002: class declaration without a name"))?;
    let body = child_of_kind(node, "class_body")
        .ok_or_else(|| anyhow!("DMX2002: class `{name}` has no body"))?;

    let mut fields = Vec::new();
    let mut methods = Vec::new();
    let mut cursor = body.walk();
    for member in body.children(&mut cursor) {
        if member.kind() != "class_member" {
            continue;
        }
        read_fields(member, src, &name, &mut fields)?;
        if let Some(method) = read_method(member, src) {
            methods.push(method);
        }
    }
    let defaults = constructor_defaults(body, src);
    for field in &mut fields {
        field.default_value = defaults.get(&field.name).cloned();
    }
    let (region, region_error) = split_region(find_region(body, src, &name));
    Ok(RawDecl {
        kind: DeclKind::Class,
        annotations: annotations_of(node, src),
        modifiers: modifiers_of(node, src),
        type_params: child_of_kind(node, "type_parameters")
            .map(|n| text(n, src).to_owned())
            .unwrap_or_default(),
        extends: child_of_kind(node, "superclass")
            .and_then(|s| child_of_kind(s, "type"))
            .map(|t| bare_type_name(text(t, src))),
        interfaces: child_of_kind(node, "interfaces")
            .map(|i| {
                let mut c = i.walk();
                i.children(&mut c)
                    .filter(|n| n.kind() == "type")
                    .map(|n| bare_type_name(text(n, src)))
                    .filter(|n| !n.starts_with('<'))
                    .collect()
            })
            .unwrap_or_default(),
        fields,
        values: Vec::new(),
        methods,
        region,
        region_error,
        close_brace: body.end_byte().saturating_sub(1),
        values_terminated: true,
        name,
    })
}

/// Reads one `enum_declaration` into the shape a macro sees.
fn read_enum(node: Node<'_>, src: &str) -> Result<RawDecl> {
    let name = child_of_kind(node, "identifier")
        .map(|n| text(n, src).to_owned())
        .ok_or_else(|| anyhow!("DMX2002: enum declaration without a name"))?;
    let body = child_of_kind(node, "enum_body")
        .ok_or_else(|| anyhow!("DMX2002: enum `{name}` has no body"))?;

    let mut values = Vec::new();
    let mut values_terminated = false;
    let mut cursor = body.walk();
    for child in body.children(&mut cursor) {
        match child.kind() {
            "enum_constant" => {
                if let Some(id) = child_of_kind(child, "identifier") {
                    values.push(RawValue {
                        name: text(id, src).to_owned(),
                        annotations: annotations_of(child, src),
                    });
                }
            }
            ";" => values_terminated = true,
            _ => {}
        }
    }
    let (region, region_error) = split_region(find_region(body, src, &name));
    Ok(RawDecl {
        kind: DeclKind::Enum,
        annotations: annotations_of(node, src),
        modifiers: Vec::new(),
        type_params: String::new(),
        extends: None,
        interfaces: Vec::new(),
        fields: Vec::new(),
        values,
        methods: Vec::new(),
        region,
        region_error,
        close_brace: body.end_byte().saturating_sub(1),
        values_terminated,
        name,
    })
}

/// A malformed fold is only an error for a declaration a macro is generating
/// into, so it travels with the declaration rather than aborting the file.
fn split_region(found: Result<Option<Region>>) -> (Option<Region>, Option<String>) {
    match found {
        Ok(region) => (region, None),
        Err(e) => (None, Some(e.to_string())),
    }
}

/// `Base<T>` names the type `Base`; a macro resolves siblings by bare name
/// [frontend.no-type-inference].
fn bare_type_name(text: &str) -> String {
    text.split(['<', ' '])
        .next()
        .unwrap_or(text)
        .trim()
        .to_owned()
}

/// The modifiers written before the `class` keyword.
fn modifiers_of(node: Node<'_>, src: &str) -> Vec<String> {
    let mut cursor = node.walk();
    node.children(&mut cursor)
        .take_while(|c| c.kind() != "identifier")
        .filter(|c| {
            matches!(
                c.kind(),
                "sealed" | "abstract" | "final" | "base" | "interface" | "mixin"
            )
        })
        .map(|c| text(c, src).to_owned())
        .collect()
}

/// Extracts instance `final` fields from one `class_member` node.
fn read_fields(member: Node<'_>, src: &str, class: &str, out: &mut Vec<RawField>) -> Result<()> {
    let annotations = annotations_of(member, src);
    let Some(decl) = child_of_kind(member, "declaration") else {
        return Ok(());
    };
    let mut is_final = false;
    let mut is_static = false;
    let mut type_text = None;
    let mut names = Vec::new();
    let mut cursor = decl.walk();
    for child in decl.children(&mut cursor) {
        match child.kind() {
            "final" => is_final = true,
            "static" | "const" | "late" => is_static = true,
            "type" => type_text = Some(text(child, src).split_whitespace().collect::<String>()),
            "initialized_identifier_list" => {
                let mut c2 = child.walk();
                for item in child.children(&mut c2) {
                    if item.kind() == "initialized_identifier"
                        && let Some(id) = child_of_kind(item, "identifier")
                    {
                        names.push(text(id, src).to_owned());
                    }
                }
            }
            _ => {}
        }
    }
    if !is_final || is_static || names.is_empty() {
        return Ok(());
    }
    if type_text.is_none() {
        bail!(
            "DMX2001: field `{}` in class `{class}` needs an explicit type",
            names.join(", ")
        );
    }
    for name in names {
        out.push(RawField {
            name,
            type_text: type_text.clone(),
            annotations: annotations.clone(),
            default_value: None,
        });
    }
    Ok(())
}

/// Defaults declared on the class's constructors, by the field they initialise.
///
/// `const Options({this.jobs = 4})` says what an omitted `jobs` is, once, where
/// a reader already looks. Restating it in an annotation would be a second
/// place to change it and a first place to get it wrong.
fn constructor_defaults(body: Node<'_>, src: &str) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    let mut cursor = body.walk();
    for member in body.children(&mut cursor) {
        let Some(decl) = child_of_kind(member, "declaration") else {
            continue;
        };
        let signature = child_of_kind(decl, "constructor_signature")
            .or_else(|| child_of_kind(decl, "constant_constructor_signature"));
        let Some(list) = signature.and_then(|s| child_of_kind(s, "formal_parameter_list")) else {
            continue;
        };
        collect_defaults(list, src, &mut out);
    }
    out
}

/// Pairs each `this.<name>` parameter with the expression that follows its `=`.
fn collect_defaults(list: Node<'_>, src: &str, out: &mut BTreeMap<String, String>) {
    let mut cursor = list.walk();
    for group in list.children(&mut cursor) {
        if group.kind() != "optional_formal_parameters" {
            continue;
        }
        let mut inner = group.walk();
        let mut pending: Option<String> = None;
        for item in group.children(&mut inner) {
            match item.kind() {
                "formal_parameter" => pending = initialised_field(item, src),
                "=" | ":" | "required" => {}
                "," | "{" | "}" | "[" | "]" => pending = None,
                _ => {
                    if let Some(name) = pending.take() {
                        // A later constructor wins, which is what a
                        // redirecting one means.
                        drop(out.insert(name, text(item, src).trim().to_owned()));
                    }
                }
            }
        }
    }
}

/// The field a `this.<name>` parameter initialises, if that is what it is.
fn initialised_field(param: Node<'_>, src: &str) -> Option<String> {
    child_of_kind(param, "constructor_param")
        .and_then(|p| child_of_kind(p, "identifier"))
        .map(|id| text(id, src).to_owned())
}

/// Reads one abstract member — a signature with no body. A method that *has* a
/// body is the author's own implementation and is deliberately invisible here:
/// what a macro implements is exactly what the interface leaves open.
fn read_method(member: Node<'_>, src: &str) -> Option<RawMethod> {
    let decl = child_of_kind(member, "declaration")?;
    let (signature, is_getter) = child_of_kind(decl, "function_signature")
        .map(|n| (n, false))
        .or_else(|| child_of_kind(decl, "getter_signature").map(|n| (n, true)))?;
    let name = child_of_kind(signature, "identifier").map(|n| text(n, src).to_owned())?;
    Some(RawMethod {
        return_type: child_of_kind(signature, "type")
            .map(|n| text(n, src).split_whitespace().collect::<String>()),
        params: child_of_kind(signature, "formal_parameter_list")
            .map(|list| read_params(list, src))
            .unwrap_or_default(),
        annotations: annotations_of(member, src),
        is_getter,
        name,
    })
}

/// Reads a parameter list, positional parameters first.
fn read_params(list: Node<'_>, src: &str) -> Vec<RawParam> {
    let mut out = Vec::new();
    let mut cursor = list.walk();
    for child in list.children(&mut cursor) {
        match child.kind() {
            "formal_parameter" => out.push(read_param(child, src, false, false)),
            // `{a, b}` are named, `[a, b]` are optional positional.
            "optional_formal_parameters" => {
                let named = text(child, src).starts_with('{');
                let mut required = false;
                let mut inner = child.walk();
                let mut pending: Option<usize> = None;
                // A named parameter's metadata is inlined beside it rather
                // than inside it, so annotations accumulate until the
                // parameter they belong to arrives.
                let mut metadata: Vec<RawAnnotation> = Vec::new();
                for item in child.children(&mut inner) {
                    match item.kind() {
                        "annotation" => metadata.extend(read_annotation(item, src)),
                        "required" => required = true,
                        "formal_parameter" => {
                            let mut param = read_param(item, src, named, named && required);
                            param.annotations.append(&mut metadata);
                            out.push(param);
                            // The default, if there is one, is the next
                            // expression after this parameter's `=`.
                            pending = Some(out.len().saturating_sub(1));
                            required = false;
                        }
                        "=" | ":" => {}
                        "," | "{" | "}" | "[" | "]" => pending = None,
                        _ => {
                            if let Some(param) = pending.take().and_then(|at| out.get_mut(at)) {
                                param.default_value = Some(text(item, src).to_owned());
                            }
                        }
                    }
                }
            }
            _ => {}
        }
    }
    out
}

/// Reads one parameter, without the default that may follow it.
fn read_param(node: Node<'_>, src: &str, is_named: bool, is_required: bool) -> RawParam {
    RawParam {
        name: child_of_kind(node, "identifier")
            .map(|n| text(n, src).to_owned())
            .unwrap_or_default(),
        type_text: child_of_kind(node, "type")
            .map(|n| text(n, src).split_whitespace().collect::<String>()),
        is_named,
        is_required,
        default_value: None,
        annotations: annotations_of(node, src),
    }
}

/// [emission.inline-backend.region-location] Region location.
///
/// The divider is recognised **structurally**, not by a magic string: a
/// `comment` token that is a *direct child of the body* of a declaration,
/// whose text is exactly `//#region`. Two consequences fall out:
///
/// * A marker inside a string literal, a nested class, or a method body is a
///   different CST position and can never match.
/// * A *labelled* fold like `//#region Helpers` belongs to the author. dmx
///   owns only the unlabelled one (and the legacy qualified one it used to
///   write), so hand-written folds coexist with it.
fn find_region(body: Node<'_>, src: &str, decl: &str) -> Result<Option<Region>> {
    // Labelled and unlabelled folds share one closing token, so openers are
    // paired with `//#endregion` by nesting, exactly as an editor folds them.
    // Only the pair whose opener is dmx's belongs to dmx.
    let mut open: Vec<bool> = Vec::new();
    let mut mine: Option<(Node<'_>, Node<'_>)> = None;
    let mut opener: Option<Node<'_>> = None;
    let mut cursor = body.walk();
    for child in body.children(&mut cursor) {
        if child.kind() != "comment" {
            continue;
        }
        let comment = text(child, src).trim();
        if let Some(is_mine) = region_opener(comment) {
            open.push(is_mine);
            if is_mine {
                opener = Some(child);
            }
        } else if is_region_end(comment) {
            match open.pop() {
                Some(true) if mine.is_some() => {
                    bail!("DMX6102: `{decl}` has more than one `{REGION_START}` divider")
                }
                Some(true) => mine = opener.take().map(|o| (o, child)),
                Some(false) => {}
                None => bail!("DMX6102: unmatched `{REGION_END}` in `{decl}`"),
            }
        }
    }
    if !open.is_empty() {
        bail!("DMX6102: unmatched `{REGION_START}` in `{decl}`");
    }
    // The region spans whole lines: from the divider's indent to the closing
    // token, so splicing replaces it without disturbing its surroundings.
    Ok(mine.map(|(s, e)| Region {
        start: line_start(src, s.start_byte()),
        end: e.end_byte(),
    }))
}

/// Every annotation attached directly to `node`.
fn annotations_of(node: Node<'_>, src: &str) -> Vec<RawAnnotation> {
    let mut cursor = node.walk();
    node.children(&mut cursor)
        .filter(|child| child.kind() == "annotation")
        .filter_map(|child| read_annotation(child, src))
        .collect()
}

/// Reads one annotation, name and arguments unevaluated.
///
/// `@dmx('macro', {…})` — the single trigger [surface.annotations] — is
/// normalized here: the macro string becomes the name, the map literal's
/// entries become the named arguments. Anything else is kept verbatim as a
/// foreign annotation.
fn read_annotation(node: Node<'_>, src: &str) -> Option<RawAnnotation> {
    let name = node
        .child_by_field_name("name")
        .map(|n| text(n, src).split_whitespace().collect::<String>())?;
    let (mut args, mut positional) = (Vec::new(), Vec::new());
    if let Some(arglist) = child_of_kind(node, "annotation_arguments") {
        collect_args(arglist, src, &mut args, &mut positional);
    }
    if name == "dmx" {
        return Some(normalize_dmx(src, &positional));
    }
    Some(RawAnnotation {
        name,
        args,
        dmx: false,
    })
}

/// `@dmx('macro', {…})` as a [`RawAnnotation`] named for its macro
/// [surface.annotations].
///
/// A `@dmx` whose first argument is not a string literal keeps the name
/// `dmx`, which no macro answers to — [`crate::macros::expand`] reports it
/// instead of guessing.
fn normalize_dmx(src: &str, positional: &[Node<'_>]) -> RawAnnotation {
    let name = positional
        .first()
        .map(|n| text(*n, src).trim().to_owned())
        .filter(|t| t.starts_with('\'') || t.starts_with('"'))
        .map(|t| crate::casing::unquote(&t));
    let mut args = Vec::new();
    for entry in positional.iter().skip(1) {
        map_entries(*entry, src, &mut args);
    }
    RawAnnotation {
        name: name.unwrap_or_else(|| "dmx".to_owned()),
        args,
        dmx: true,
    }
}

/// The `'key': value` entries of a map literal, keys unquoted and values as
/// raw Dart source [surface.annotations].
fn map_entries(node: Node<'_>, src: &str, out: &mut Vec<(String, String)>) {
    let mut cursor = node.walk();
    for child in node.children(&mut cursor) {
        if child.kind() == "pair" {
            let key = child
                .child_by_field_name("key")
                .or_else(|| child.named_child(0));
            let mut inner = child.walk();
            let value = child
                .child_by_field_name("value")
                .or_else(|| child.named_children(&mut inner).last());
            if let (Some(key), Some(value)) = (key, value) {
                out.push((
                    crate::casing::unquote(text(key, src)),
                    text(value, src).to_owned(),
                ));
            }
        }
    }
}

/// Sorts an argument list into named and positional argument nodes, recursing
/// through the wrapper nodes the grammar puts between them. Positional
/// arguments stay as nodes so `@dmx`'s map literal keeps its structure.
fn collect_args<'a>(
    node: Node<'a>,
    src: &str,
    named: &mut Vec<(String, String)>,
    positional: &mut Vec<Node<'a>>,
) {
    let mut cursor = node.walk();
    for child in node.children(&mut cursor) {
        match child.kind() {
            "named_argument" => {
                let label = child_of_kind(child, "label")
                    .map(|l| text(l, src).trim_end_matches(':').trim().to_owned());
                // The value is whatever trails the label, taken as the last child
                // rather than by index so no arithmetic can run off the end.
                let mut inner = child.walk();
                let value = child.children(&mut inner).last();
                if let (Some(label), Some(value)) = (label, value) {
                    named.push((label, text(value, src).to_owned()));
                }
            }
            "annotation_open_paren" | "(" | ")" | "," => {}
            "arguments" | "argument_part" | "argument_list" => {
                collect_args(child, src, named, positional);
            }
            _ => positional.push(child),
        }
    }
}

/// The first direct child of `node` with this kind.
fn child_of_kind<'a>(node: Node<'a>, kind: &str) -> Option<Node<'a>> {
    let mut cursor = node.walk();
    node.children(&mut cursor).find(|c| c.kind() == kind)
}

/// The source text `node` spans.
fn text<'a>(node: Node<'_>, src: &'a str) -> &'a str {
    &src[node.byte_range()]
}

/// The byte offset of the start of the line `byte` falls on.
#[must_use]
pub fn line_start(src: &str, byte: usize) -> usize {
    src.get(..byte)
        .and_then(|before| before.rfind('\n'))
        .map_or(0, |at| at.saturating_add(1))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// dmx owns the bare divider and the legacy qualified one; a labelled fold
    /// is the author's [emission.inline-backend.region-location].
    #[test]
    fn divider_ownership() {
        assert_eq!(region_opener("//#region"), Some(true));
        assert_eq!(
            region_opener("//#region dmx:generated builtin/model@0.1.0 b3:abc"),
            Some(true)
        );
        assert_eq!(region_opener("//#region Helpers"), Some(false));
        assert_eq!(region_opener("//#regionalise"), None);
        assert_eq!(region_opener("// not a region"), None);
        assert!(is_region_end("//#endregion"));
        assert!(is_region_end("//#endregion dmx:generated"));
        assert!(!is_region_end("//#endregion Helpers"));
    }

    #[test]
    fn reads_enums_and_interfaces() {
        let mut fe = Frontend::new().unwrap();
        let decls = fe
            .declarations(
                "enum Status { a, @dmx('key', {'name': 'B'}) b; }\n\
                 abstract class Repo { Future<int> count(); int get size; }\n\
                 class Fake implements Repo, Other {}\n\
                 sealed class Shape<T> {}",
            )
            .unwrap();
        assert_eq!(decls.len(), 4);
        assert_eq!(decls[0].kind, DeclKind::Enum);
        assert!(decls[0].values_terminated);
        assert_eq!(decls[0].values[1].name, "b");
        assert_eq!(decls[0].values[1].annotations[0].arg("name"), Some("'B'"));
        assert_eq!(decls[1].methods.len(), 2);
        assert_eq!(
            decls[1].methods[0].return_type.as_deref(),
            Some("Future<int>")
        );
        assert!(decls[1].methods[1].is_getter);
        assert_eq!(decls[2].interfaces, vec!["Repo", "Other"]);
        assert!(decls[3].has_modifier("sealed"));
        assert_eq!(decls[3].type_args(), "<T>");
    }

    #[test]
    fn reads_parameters() {
        let mut fe = Frontend::new().unwrap();
        let decls = fe
            .declarations("abstract class A { void f(int a, {required String b, int c = 3}); }")
            .unwrap();
        let params = &decls[0].methods[0].params;
        assert_eq!(params.len(), 3);
        assert!(!params[0].is_named && params[0].type_text.as_deref() == Some("int"));
        assert!(params[1].is_named && params[1].is_required);
        assert_eq!(params[2].default_value.as_deref(), Some("3"));
    }

    /// [surface.annotations]: `@dmx('macro', {…})` normalizes to its macro
    /// name, with the map literal's entries as the named arguments.
    #[test]
    fn reads_annotation_arguments() {
        let mut fe = Frontend::new().unwrap();
        let decls = fe
            .declarations("@dmx('route', {'pattern': '/orders/:id', 'name': 'order'}) class R {}")
            .unwrap();
        let route = decls[0].annotation("route").unwrap();
        assert!(route.dmx);
        assert_eq!(route.arg("pattern"), Some("'/orders/:id'"));
        assert_eq!(route.arg("name"), Some("'order'"));
    }

    /// A foreign annotation keeps its own name and never reads as a trigger,
    /// and a `@dmx` without a string macro name keeps the name `dmx` for
    /// [`crate::macros::expand`] to refuse [surface.annotations].
    #[test]
    fn foreign_and_malformed_annotations_stay_inert() {
        let mut fe = Frontend::new().unwrap();
        let decls = fe
            .declarations("@Deprecated('gone') @dmx(model) class R {}")
            .unwrap();
        assert!(decls[0].annotation("Deprecated").is_none());
        assert!(!decls[0].annotations[0].dmx);
        assert_eq!(decls[0].annotations[0].name, "Deprecated");
        assert!(decls[0].annotations[1].dmx);
        assert_eq!(decls[0].annotations[1].name, "dmx");
    }

    /// A broken fold in a declaration no macro touches is not dmx's business.
    #[test]
    fn region_damage_travels_with_its_declaration() {
        let mut fe = Frontend::new().unwrap();
        let decls = fe.declarations("class A { //#region\n }").unwrap();
        assert!(decls[0].region_error.is_some());
    }
}
